// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPlM1xyeEYhap-xrWtsCwEEofdYU3rbfs',
    appId: '1:126886032261:web:27aa2c21cfc8ace3758aec',
    messagingSenderId: '126886032261',
    projectId: 'aquasafe-6023f',
    authDomain: 'aquasafe-6023f.firebaseapp.com',
    storageBucket: 'aquasafe-6023f.firebasestorage.app',
    measurementId: 'G-X6MTEMSW6S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGS717yDJpuPJa1VCrpkGHz8ObvAZRUAE',
    appId: '1:126886032261:android:36d8a7f1a71679b2758aec',
    messagingSenderId: '126886032261',
    projectId: 'aquasafe-6023f',
    storageBucket: 'aquasafe-6023f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGcuyhaPUw_xTpl93wPlFFUq4ibp9e50s',
    appId: '1:126886032261:ios:a184d3fc86ba8522758aec',
    messagingSenderId: '126886032261',
    projectId: 'aquasafe-6023f',
    storageBucket: 'aquasafe-6023f.firebasestorage.app',
    iosBundleId: 'com.example.aquasafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGcuyhaPUw_xTpl93wPlFFUq4ibp9e50s',
    appId: '1:126886032261:ios:a184d3fc86ba8522758aec',
    messagingSenderId: '126886032261',
    projectId: 'aquasafe-6023f',
    storageBucket: 'aquasafe-6023f.firebasestorage.app',
    iosBundleId: 'com.example.aquasafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPlM1xyeEYhap-xrWtsCwEEofdYU3rbfs',
    appId: '1:126886032261:web:c2af2e51cf044430758aec',
    messagingSenderId: '126886032261',
    projectId: 'aquasafe-6023f',
    authDomain: 'aquasafe-6023f.firebaseapp.com',
    storageBucket: 'aquasafe-6023f.firebasestorage.app',
    measurementId: 'G-6P5QRB4RM5',
  );
}
